spring:
  application:
    name: inventory-worker
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-workers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        max.poll.records: 1000
        fetch.max.bytes: 52428800
        max.partition.fetch.bytes: 52428800
  data:
    redis:
      host: localhost
      port: 6379
